std = "lua51"
max_line_length = false
ignore = {
   "211",
   "212",
   "213",
   "6..",
}
globals = {
   "bit",
   "ChatFontNormal",
   "COMBATLOG_OBJECT_REACTION_HOSTILE",
   "COMBATLOG_OBJECT_TYPE_PLAYER",
   "CreateFrame",
   "date",
   "DEFAULT_CHAT_FRAME",
   "GetAddOnMetadata",
   "GetBattlefieldInstanceRunTime",
   "GetBattlefieldScore",
   "GetBattlefieldTeamInfo",
   "GetBattlefieldWinner",
   "GetNumBattlefieldScores",
   "GetRealZoneText",
   "GameTooltip",
   "IsActiveBattlefieldArena",
   "IsInInstance",
   "Minimap",
   "SlashCmdList",
   "SLASH_TDARENALENS1",
   "SLASH_TDARENALENS2",
   "TDArenaLensCharDB",
   "TDArenaLensDB",
   "time",
   "UIParent",
   "UnitName",
}
